# Generated by Django 6.1 on 2026-08-09 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quote_number', models.CharField(db_index=True, editable=False, max_length=50, unique=True)),
                ('client_name', models.CharField(max_length=255)),
                ('client_email', models.EmailField(max_length=254)),
                ('client_phone', models.CharField(max_length=50)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('project_title', models.CharField(max_length=255)),
                ('project_overview', models.TextField(blank=True)),
                ('detailed_requirements', models.TextField()),
                ('additional_features', models.JSONField(blank=True, default=list, help_text='Custom selected add-on modules')),
                ('requirements_doc', models.FileField(blank=True, null=True, upload_to='quotes/docs/')),
                ('estimated_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('expected_deadline', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('under_review', 'Under Review'), ('quoted', 'Quote Issued'), ('accepted', 'Accepted by Client'), ('rejected', 'Rejected by Client'), ('invoice_generated', 'Invoice Generated'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=25)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quote_requests', to=settings.AUTH_USER_MODEL)),
                ('software_item', models.ForeignKey(blank=True, help_text='Optional reference software product', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.softwareitem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuoteProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proposal_number', models.CharField(db_index=True, editable=False, max_length=50, unique=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('proposed_cost', models.DecimalField(decimal_places=2, help_text='Grand Total proposed cost', max_digits=12)),
                ('estimated_delivery_days', models.PositiveIntegerField(default=14)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('scope_of_work', models.TextField()),
                ('deliverables', models.TextField(blank=True)),
                ('payment_terms', models.TextField(blank=True, default='50% upfront deposit, 50% upon final delivery.')),
                ('terms_and_conditions', models.TextField(blank=True)),
                ('is_approved_by_client', models.BooleanField(default=False)),
                ('client_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('pdf_proposal', models.FileField(blank=True, null=True, upload_to='proposals/pdf/')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('quote_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proposal', to='quotes.quoterequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
