# Generated by Django 6.1 on 2026-08-09 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transaction_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('transaction_type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], default='income', max_length=10)),
                ('category', models.CharField(help_text='e.g. Software Sale, Hosting Fee, Freelancer Payout', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('payment_method', models.CharField(choices=[('bank', 'Bank Transfer'), ('card', 'Credit/Debit Card'), ('paypal', 'PayPal'), ('stripe', 'Stripe'), ('cash', 'Cash'), ('other', 'Other')], default='bank', max_length=20)),
                ('reference_type', models.CharField(choices=[('order', 'Order Invoice'), ('quote', 'Quote Proposal'), ('freelancer', 'Freelancer Payout'), ('general', 'General Ledger')], default='general', max_length=20)),
                ('reference_id', models.CharField(blank=True, max_length=100)),
                ('transaction_date', models.DateField(db_index=True)),
                ('notes', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='accounting/receipts/')),
            ],
            options={
                'verbose_name': 'Financial Transaction',
                'verbose_name_plural': 'Financial Accounting Ledger',
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='category',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='author',
        ),
        migrations.RemoveField(
            model_name='freelancerprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='freelancer',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='job',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='client',
        ),
        migrations.RemoveField(
            model_name='order',
            name='client',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.RemoveField(
            model_name='quoteproposal',
            name='quote_request',
        ),
        migrations.RemoveField(
            model_name='quoterequest',
            name='client',
        ),
        migrations.RemoveField(
            model_name='quoterequest',
            name='software_item',
        ),
        migrations.RemoveField(
            model_name='softwareitem',
            name='category',
        ),
        migrations.AlterModelOptions(
            name='siteconfiguration',
            options={'verbose_name': 'Site & SEO Configuration', 'verbose_name_plural': 'Site & SEO Configuration'},
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='bank_details',
            field=models.TextField(blank=True, help_text='Bank Account Info for Wire Transfers'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='company_tax_id',
            field=models.CharField(blank=True, help_text='TAX / VAT / Registration Number', max_length=100),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='custom_footer_scripts',
            field=models.TextField(blank=True, help_text='Raw JS/HTML injected before </body>'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='custom_header_scripts',
            field=models.TextField(blank=True, help_text='Raw JS/HTML injected into <head>'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='dark_logo',
            field=models.ImageField(blank=True, null=True, upload_to='system/logo/'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='default_meta_description',
            field=models.TextField(default='Leading platform for enterprise software, freelancer talent, and digital products.'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='default_meta_keywords',
            field=models.CharField(default='software, ecommerce, freelancers, quotes, web development', max_length=255),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='default_meta_title',
            field=models.CharField(default='NewInfrizo - Premium Software & Digital Marketplace', max_length=255),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='default_og_image',
            field=models.ImageField(blank=True, null=True, upload_to='system/seo/'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='digital_signature',
            field=models.ImageField(blank=True, null=True, upload_to='system/signature/'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='google_analytics_id',
            field=models.CharField(blank=True, help_text='GA4 Measurement ID (e.g. G-XXXXXXX)', max_length=100),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='google_site_verification',
            field=models.CharField(blank=True, help_text='Google Search Console verification meta string', max_length=255),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='google_tag_manager_id',
            field=models.CharField(blank=True, help_text='GTM Container ID (e.g. GTM-XXXXXXX)', max_length=100),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='robots_txt_content',
            field=models.TextField(blank=True, help_text='Custom robots.txt rules'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='social_facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='social_github',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='social_linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='social_twitter',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='social_youtube',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='support_email',
            field=models.EmailField(default='support@newinfrizo.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='company_tagline',
            field=models.CharField(default='Next-Gen Software Solutions & Digital Marketplace', max_length=255),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='currency_code',
            field=models.CharField(default='USD', max_length=10),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='currency_symbol',
            field=models.CharField(default='$', max_length=10),
        ),
        migrations.DeleteModel(
            name='BlogCategory',
        ),
        migrations.DeleteModel(
            name='BlogPost',
        ),
        migrations.DeleteModel(
            name='FreelancerProfile',
        ),
        migrations.DeleteModel(
            name='JobApplication',
        ),
        migrations.DeleteModel(
            name='JobPost',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='QuoteProposal',
        ),
        migrations.DeleteModel(
            name='QuoteRequest',
        ),
        migrations.DeleteModel(
            name='SoftwareCategory',
        ),
        migrations.DeleteModel(
            name='SoftwareItem',
        ),
    ]
