# Generated by Django 6.1 on 2026-08-09 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SoftwareCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(blank=True, help_text="CSS icon class e.g. 'ri-code-s-slash-line'", max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='catalog.softwarecategory')),
            ],
            options={
                'verbose_name_plural': 'Software Categories',
            },
        ),
        migrations.CreateModel(
            name='SoftwareItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('version', models.CharField(default='1.0.0', max_length=50)),
                ('short_description', models.CharField(max_length=500)),
                ('detailed_description', models.TextField(help_text='Full Envato-style details & documentation overview')),
                ('thumbnail', models.ImageField(upload_to='software/thumbnails/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='software/banners/')),
                ('live_preview_url', models.URLField(blank=True, null=True)),
                ('video_demo_url', models.URLField(blank=True, null=True)),
                ('video_demo_file', models.FileField(blank=True, null=True, upload_to='software/videos/')),
                ('tech_stack', models.JSONField(default=list, help_text="e.g. ['Django', 'React', 'PostgreSQL']")),
                ('frameworks', models.CharField(blank=True, help_text='e.g. Django 6.1, React 19, Tailwind', max_length=255)),
                ('compatible_browsers', models.CharField(default='Chrome, Firefox, Safari, Edge', max_length=255)),
                ('documentation_url', models.URLField(blank=True, null=True)),
                ('documentation_file', models.FileField(blank=True, null=True, upload_to='software/docs/')),
                ('regular_price', models.DecimalField(decimal_places=2, help_text='Single project license', max_digits=12)),
                ('extended_price', models.DecimalField(blank=True, decimal_places=2, help_text='Multi-client / reseller license', max_digits=12, null=True)),
                ('sales_count', models.PositiveIntegerField(default=0)),
                ('rating_average', models.DecimalField(decimal_places=2, default=5.0, max_digits=3)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_trending', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='softwares', to='catalog.softwarecategory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SoftwareGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='software/gallery/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='catalog.softwareitem')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='SoftwareFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, default='ri-check-line', max_length=100)),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='catalog.softwareitem')),
            ],
        ),
        migrations.CreateModel(
            name='SoftwareChangelog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50)),
                ('release_date', models.DateField()),
                ('change_notes', models.TextField()),
                ('software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changelogs', to='catalog.softwareitem')),
            ],
            options={
                'ordering': ['-release_date'],
            },
        ),
    ]
